import type { QuizQuestion } from '@/types'

export const quizQuestions: QuizQuestion[] = [
  {
    id: 'tenure',
    step: 1,
    question: 'Do you own your home or are you renting?',
    helpText: "This affects which camera types make most sense — renters have different constraints to homeowners.",
    inputType: 'single',
    answers: [
      {
        id: 'own-home',
        label: 'I own my home',
        icon: '🏠',
        scores: {
          'wifi-diy-ecosystem': 5,
          'local-storage-no-sub': 5,
          'poe-nvr-system': 10,
          'battery-solar': 5,
          'hybrid': 5,
        },
      },
      {
        id: 'renting',
        label: "I'm renting",
        icon: '🔑',
        helpText: "Battery and plug-in cameras are usually the safest choice for renters",
        scores: {
          'wifi-diy-ecosystem': 8,
          'local-storage-no-sub': 5,
          'poe-nvr-system': 0,
          'battery-solar': 10,
          'hybrid': 3,
        },
      },
      {
        id: 'business',
        label: "It's a business property",
        icon: '🏢',
        scores: {
          'wifi-diy-ecosystem': 3,
          'local-storage-no-sub': 5,
          'poe-nvr-system': 12,
          'battery-solar': 2,
          'hybrid': 5,
        },
      },
    ],
  },
  {
    id: 'budget',
    step: 2,
    question: "What's your total budget for the whole system?",
    helpText: 'Include cameras, any hub or recorder, and installation if you need it.',
    inputType: 'single',
    answers: [
      {
        id: 'under-500',
        label: 'Under NZ$500',
        icon: '💰',
        scores: {
          'wifi-diy-ecosystem': 8,
          'local-storage-no-sub': 6,
          'poe-nvr-system': 0,
          'battery-solar': 8,
          'hybrid': 3,
        },
      },
      {
        id: '500-1500',
        label: 'NZ$500 – $1,500',
        icon: '💳',
        scores: {
          'wifi-diy-ecosystem': 6,
          'local-storage-no-sub': 8,
          'poe-nvr-system': 5,
          'battery-solar': 6,
          'hybrid': 8,
        },
      },
      {
        id: '1500-plus',
        label: 'Over NZ$1,500',
        icon: '💎',
        helpText: 'Full PoE / NVR systems and professional installs become realistic at this budget',
        scores: {
          'wifi-diy-ecosystem': 3,
          'local-storage-no-sub': 6,
          'poe-nvr-system': 12,
          'battery-solar': 4,
          'hybrid': 8,
        },
      },
    ],
  },
  {
    id: 'camera-count',
    step: 3,
    question: 'How many cameras do you think you need?',
    helpText: "Not sure? A typical 3-bedroom home usually needs 3–4 cameras for good coverage.",
    inputType: 'single',
    answers: [
      {
        id: '1-2',
        label: '1–2 cameras',
        icon: '📷',
        helpText: 'Front door or a single entry point',
        scores: {
          'wifi-diy-ecosystem': 10,
          'local-storage-no-sub': 8,
          'poe-nvr-system': 2,
          'battery-solar': 10,
          'hybrid': 5,
        },
      },
      {
        id: '3-4',
        label: '3–4 cameras',
        icon: '📸',
        helpText: 'Most home setups',
        scores: {
          'wifi-diy-ecosystem': 8,
          'local-storage-no-sub': 10,
          'poe-nvr-system': 6,
          'battery-solar': 6,
          'hybrid': 10,
        },
      },
      {
        id: '5-plus',
        label: '5 or more cameras',
        icon: '🎥',
        helpText: 'Full-property coverage or larger homes',
        scores: {
          'wifi-diy-ecosystem': 3,
          'local-storage-no-sub': 5,
          'poe-nvr-system': 15,
          'battery-solar': 2,
          'hybrid': 6,
        },
      },
    ],
  },
  {
    id: 'subscription',
    step: 4,
    question: 'Are you comfortable paying a monthly subscription?',
    inputType: 'single',
    answers: [
      {
        id: 'yes-fine',
        label: "Yes — if it's worth it",
        icon: '✅',
        helpText: 'Cloud storage and monitoring can be genuinely useful',
        scores: {
          'wifi-diy-ecosystem': 12,
          'local-storage-no-sub': 3,
          'poe-nvr-system': 5,
          'battery-solar': 8,
          'hybrid': 6,
        },
      },
      {
        id: 'prefer-not',
        label: "I'd prefer to avoid it",
        icon: '😐',
        scores: {
          'wifi-diy-ecosystem': 4,
          'local-storage-no-sub': 10,
          'poe-nvr-system': 8,
          'battery-solar': 6,
          'hybrid': 8,
        },
      },
      {
        id: 'definitely-not',
        label: "Definitely not — no ongoing fees",
        icon: '🚫',
        helpText: 'Local storage systems make this possible',
        scores: {
          'wifi-diy-ecosystem': 0,
          'local-storage-no-sub': 15,
          'poe-nvr-system': 10,
          'battery-solar': 5,
          'hybrid': 3,
        },
      },
    ],
  },
  {
    id: 'power',
    step: 5,
    question: 'Can you run power cables to where the cameras will go?',
    helpText: 'This affects whether wired cameras are an option for you.',
    inputType: 'single',
    answers: [
      {
        id: 'yes-power-available',
        label: "Yes — I can run power or there's an outlet nearby",
        icon: '🔌',
        scores: {
          'wifi-diy-ecosystem': 5,
          'local-storage-no-sub': 5,
          'poe-nvr-system': 12,
          'battery-solar': 3,
          'hybrid': 8,
        },
      },
      {
        id: 'no-battery-only',
        label: "No — battery or solar only",
        icon: '🔋',
        scores: {
          'wifi-diy-ecosystem': 8,
          'local-storage-no-sub': 6,
          'poe-nvr-system': 0,
          'battery-solar': 15,
          'hybrid': 3,
        },
      },
      {
        id: 'some-both',
        label: "Some spots have power, some don't",
        icon: '⚡',
        scores: {
          'wifi-diy-ecosystem': 6,
          'local-storage-no-sub': 8,
          'poe-nvr-system': 6,
          'battery-solar': 6,
          'hybrid': 12,
        },
      },
    ],
  },
  {
    id: 'storage',
    step: 6,
    question: 'Where do you want your footage stored?',
    inputType: 'single',
    answers: [
      {
        id: 'cloud-only',
        label: "In the cloud — accessible anywhere",
        icon: '☁️',
        helpText: 'Easy access from anywhere, but requires ongoing subscription',
        scores: {
          'wifi-diy-ecosystem': 12,
          'local-storage-no-sub': 0,
          'poe-nvr-system': 3,
          'battery-solar': 8,
          'hybrid': 4,
        },
      },
      {
        id: 'local-only',
        label: "On my own device — no cloud",
        icon: '💾',
        helpText: 'More private, no ongoing cost, but footage stays at home',
        scores: {
          'wifi-diy-ecosystem': 0,
          'local-storage-no-sub': 15,
          'poe-nvr-system': 12,
          'battery-solar': 3,
          'hybrid': 4,
        },
      },
      {
        id: 'both-fine',
        label: "Both — cloud + local backup",
        icon: '🔄',
        scores: {
          'wifi-diy-ecosystem': 6,
          'local-storage-no-sub': 6,
          'poe-nvr-system': 8,
          'battery-solar': 5,
          'hybrid': 12,
        },
      },
      {
        id: 'not-sure',
        label: "Not sure yet",
        icon: '🤷',
        scores: {
          'wifi-diy-ecosystem': 5,
          'local-storage-no-sub': 5,
          'poe-nvr-system': 5,
          'battery-solar': 5,
          'hybrid': 5,
        },
      },
    ],
  },
  {
    id: 'install',
    step: 7,
    question: 'How comfortable are you with DIY tech setup?',
    inputType: 'single',
    answers: [
      {
        id: 'confident-diy',
        label: "Very comfortable — I'll do it myself",
        icon: '🔧',
        scores: {
          'wifi-diy-ecosystem': 8,
          'local-storage-no-sub': 10,
          'poe-nvr-system': 8,
          'battery-solar': 8,
          'hybrid': 10,
        },
      },
      {
        id: 'some-help',
        label: "I can do some things but may need help",
        icon: '🛠️',
        scores: {
          'wifi-diy-ecosystem': 10,
          'local-storage-no-sub': 6,
          'poe-nvr-system': 4,
          'battery-solar': 10,
          'hybrid': 6,
        },
      },
      {
        id: 'professional-please',
        label: "I'd prefer a professional installer",
        icon: '👷',
        helpText: 'Get Secure can install and configure your system',
        scores: {
          'wifi-diy-ecosystem': 3,
          'local-storage-no-sub': 4,
          'poe-nvr-system': 12,
          'battery-solar': 4,
          'hybrid': 6,
        },
      },
    ],
  },
  {
    id: 'priority',
    step: 8,
    question: 'What matters most to you?',
    helpText: "Pick the one thing that's most important in your decision.",
    inputType: 'single',
    answers: [
      {
        id: 'ease-of-use',
        label: "Easiest possible setup and use",
        icon: '✨',
        scores: {
          'wifi-diy-ecosystem': 15,
          'local-storage-no-sub': 4,
          'poe-nvr-system': 2,
          'battery-solar': 8,
          'hybrid': 3,
        },
      },
      {
        id: 'privacy-control',
        label: "Privacy — I control my footage",
        icon: '🔒',
        scores: {
          'wifi-diy-ecosystem': 2,
          'local-storage-no-sub': 15,
          'poe-nvr-system': 12,
          'battery-solar': 4,
          'hybrid': 5,
        },
      },
      {
        id: 'picture-quality',
        label: "Best possible video quality",
        icon: '🎬',
        helpText: 'PoE and wired cameras give the best reliable quality',
        scores: {
          'wifi-diy-ecosystem': 4,
          'local-storage-no-sub': 5,
          'poe-nvr-system': 15,
          'battery-solar': 6,
          'hybrid': 6,
        },
      },
      {
        id: 'cost-savings',
        label: "Lowest total cost over time",
        icon: '💵',
        scores: {
          'wifi-diy-ecosystem': 3,
          'local-storage-no-sub': 12,
          'poe-nvr-system': 6,
          'battery-solar': 10,
          'hybrid': 5,
        },
      },
      {
        id: 'smart-home-integration',
        label: "Works with my smart home (Alexa, Google)",
        icon: '🏡',
        scores: {
          'wifi-diy-ecosystem': 15,
          'local-storage-no-sub': 4,
          'poe-nvr-system': 3,
          'battery-solar': 8,
          'hybrid': 5,
        },
      },
    ],
  },
]
